name: publish
on: [push]

jobs:
  publish-hello-docker-image:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GH_REPO_WRITE_TOKEN }}
      - name: Build the hello-docker Docker image
        run: |
          docker build . --tag ghcr.io/jbaquino3/laravel-php-image:latest
          docker run ghcr.io/jbaquino3/laravel-php-image:latest
          docker push ghcr.io/jbaquino3/laravel-php-image:latest